function formatComment(data) {
  function formatSection(title, items) {
    if (!items || items.length === 0) return "";

    return `
      ### ${title}

      ${items.map(item => `
      - **[${item.severity}]** ${item.issue}
        - Reason: ${item.reason}
        - Fix: ${item.suggestion}
      `).join("")}
      `;
        }

        return `
      ## 🤖 AI PR Review

      ${formatSection("🐞 Bugs", data.bugs)}
      ${formatSection("⚡ Performance Issues", data.performance_issues)}
      ${formatSection("🛠 Improvements", data.improvements)}
      ${formatSection("🧪 Edge Cases", data.edge_cases)}

      ---
      Generated by AI Agent
    `;
}

module.exports = { formatComment };